# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
## 1st answer

import numpy as np

array = np.random.randint(1, 21, size=(5, 5))
print("Original array: ")
print(array)

array[:, 2] = 1
print("Modified array: ")
print(array)

Original array: 
[[13 18  7  5  9]
 [11 12  7 11 19]
 [12  6  7  2 19]
 [ 9  7 16  7  2]
 [ 2  9 17 12  9]]
Modified array: 
[[13 18  1  5  9]
 [11 12  1 11 19]
 [12  6  1  2 19]
 [ 9  7  1  7  2]
 [ 2  9  1 12  9]]


In [2]:
## 2nd answer

array = np.arange(1, 17).reshape(4, 4)
print("Original Array: ")
print(array)

np.fill_diagonal(array, 0)
print("Modified array: ")
print(array)

Original Array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array: 
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [3]:
## 3rd answer

array = np.arange(1, 37).reshape(6, 6)
print("Original Array: ")
print(array)

sub_array = array[2:5, 1:4]
print("Sub Array: ")
print(sub_array)

Original Array: 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub Array: 
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [4]:
## 4th answer

array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[ 4  6  9  6  1]
 [ 5 18  4  2 18]
 [20 14 14  1  8]
 [17  7 11 20  4]
 [19  3  7  3 17]]
Border elements:
[ 4  6  9  6  1 19  3  7  3 17  5 20 17 18  8  4]


In [5]:
## 5th answer

array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array1: ")
print(array1)
print("Array2: ")
print(array2)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addtion: ")
print(addition)
print("Element-wise subtraction: ")
print(subtraction)
print("Element-wise multiplication: ")
print(multiplication)
print("Element-wise division: ")
print(division)

Array1: 
[[3 9 4 7]
 [7 2 5 9]
 [4 1 8 9]]
Array2: 
[[10  2  6  1]
 [ 4  7  9  2]
 [ 2 10  9  1]]
Element-wise addtion: 
[[13 11 10  8]
 [11  9 14 11]
 [ 6 11 17 10]]
Element-wise subtraction: 
[[-7  7 -2  6]
 [ 3 -5 -4  7]
 [ 2 -9 -1  8]]
Element-wise multiplication: 
[[30 18 24  7]
 [28 14 45 18]
 [ 8 10 72  9]]
Element-wise division: 
[[0.3        4.5        0.66666667 7.        ]
 [1.75       0.28571429 0.55555556 4.5       ]
 [2.         0.1        0.88888889 9.        ]]


In [6]:
## 6th answer

array = np.arange(1, 17).reshape(4, 4)
print("Original Array: ")
print(array)

row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum: ")
print(row_sum)
print("Column-wise sum: ")
print(column_sum)

Original Array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum: 
[10 26 42 58]
Column-wise sum: 
[28 32 36 40]


In [7]:
## 7th answer

array = np.random.randint(1, 21, size=(5, 5))
print("Original Array: ")
print(array)

mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Original Array: 
[[18 17  1 16 12]
 [19 20  5  3 18]
 [ 2 20  9 15 19]
 [ 8 15  6 16  4]
 [ 9 18 13 12  2]]
Mean: 11.88
Median: 13.0
Standard Deviation: 6.307582738260355
Variance: 39.7856


In [8]:
## 8th answer

array = np.arange(1, 10).reshape(3, 3)
print("Original Array: ")
print(array)

mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized Array: ")
print(normalized_array)

Original Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array: 
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [9]:
## 9th answer

array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original Array: ")
print(array)
print("1D Array: ")
print(row_array)

result = array + row_array
print("Resulting array: ")
print(result)

Original Array: 
[[1 9 2]
 [6 1 9]
 [1 5 9]]
1D Array: 
[7 9 2]
Resulting array: 
[[ 8 18  4]
 [13 10 11]
 [ 8 14 11]]


In [10]:
## 10th answer

array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original Array: ")
print(array)
print("1D Array: ")
print(column_array)

result = array - column_array[:, np.newaxis]
print("Resulting array: ")
print(result)

Original Array: 
[[3 3 6 9]
 [6 8 6 4]
 [2 1 4 6]
 [2 1 7 6]]
1D Array: 
[ 3  8  1 10]
Resulting array: 
[[ 0  0  3  6]
 [-2  0 -2 -4]
 [ 1  0  3  5]
 [-8 -9 -3 -4]]


In [11]:
## 11th answer

matrix = np.random.randint(1, 11, size=(3,3))
print("Original Matrix: ")
print(matrix)

determinant = np.linalg.det(matrix)
print("Determinant: ", determinant)

inverse = np.linalg.inv(matrix)
print("Inverse: ", inverse)

eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues: ", eigenvalues)

Original Matrix: 
[[8 8 2]
 [3 6 2]
 [8 8 1]]
Determinant:  -23.999999999999993
Inverse:  [[ 0.41666667 -0.33333333 -0.16666667]
 [-0.54166667  0.33333333  0.41666667]
 [ 1.         -0.         -1.        ]]
Eigenvalues:  [14.47075914  1.57936032 -1.05011946]


In [12]:
## 12th answer

array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array1: ")
print(array1)
print("Array2: ")
print(array2)

result = np.dot(array1, array2)
print("Matrix multiplication result: ")
print(result)

Array1: 
[[ 5  5  7]
 [10  4  7]]
Array2: 
[[8 4]
 [2 9]
 [9 4]]
Matrix multiplication result: 
[[113  93]
 [151 104]]


In [13]:
## 13th answer

array = np.arange(1, 10).reshape(3, 3)
print("Original Array: ")
print(array)

reshaped_array_1 = array.reshape(1, 9)
print("Reshaped Array (1, 9): ")
print(reshaped_array_1)

reshaped_array_2 = reshaped_array_1.reshape(9, 1)
print("Reshaped Array (9, 1): ")
print(reshaped_array_2)

Original Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped Array (1, 9): 
[[1 2 3 4 5 6 7 8 9]]
Reshaped Array (9, 1): 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [14]:
## 14th answer

array = np.random.randint(1, 21, size=(5, 5))
print("Original Array: ")
print(array)

flattened_array = array.flatten()
print("Flattened Array : ")
print(flattened_array)

reshaped_array = flattened_array.reshape(5, 5)
print("Reshaped Array : ")
print(reshaped_array)

Original Array: 
[[ 3  9 12 20 18]
 [ 8 14  7 20  3]
 [18 20  6 20  6]
 [ 1 11 18 12  7]
 [ 6 17 16 14 10]]
Flattened Array : 
[ 3  9 12 20 18  8 14  7 20  3 18 20  6 20  6  1 11 18 12  7  6 17 16 14
 10]
Reshaped Array : 
[[ 3  9 12 20 18]
 [ 8 14  7 20  3]
 [18 20  6 20  6]
 [ 1 11 18 12  7]
 [ 6 17 16 14 10]]


In [15]:
## 15th answer

array = np.random.randint(1, 21, size=(5, 5))
print("Original Array: ")
print(array)

corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner Elements: ")
print(corners)

Original Array: 
[[11  9  1 18  7]
 [ 7  3 13  3 12]
 [18  6 20 13 17]
 [13 15  5  4  7]
 [ 1  1  8  3 15]]
Corner Elements: 
[11  7  1 15]


In [16]:
## 16th answer

array = np.random.randint(1, 21, size=(4, 4))
print("Original Array: ")
print(array)

array[array > 10] = 10
print("Modified Array: ")
print(array)

Original Array: 
[[11  3  2 15]
 [ 4 17 18  8]
 [ 3  8  6 20]
 [15 14 18 11]]
Modified Array: 
[[10  3  2 10]
 [ 4 10 10  8]
 [ 3  8  6 10]
 [10 10 10 10]]


In [23]:
## 17th answer

data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Zaheer', 21, 55.5), ('Asif Khan', 22, 60.1), ('Hashid', 20, 54.5)], dtype=data_type)
print("Original Array: ")
print(data)

sorted_data = np.sort(data, order='age')
print("Sorted array by age: ")
print(sorted_data)

Original Array: 
[('Zaheer', 21, 55.5) ('Asif Khan', 22, 60.1) ('Hashid', 20, 54.5)]
Sorted array by age: 
[('Hashid', 20, 54.5) ('Zaheer', 21, 55.5) ('Asif Khan', 22, 60.1)]


In [24]:
## 18th answer

data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [25]:
## 19th answer

import numpy.ma as ma

array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original Array: ")
print(array)
print("Masked Array: ")
print(masked_array)

sum_unmasked = masked_array.sum()
print("Sum of unmasked elements: ", sum_unmasked)

Original Array: 
[[ 1 10 14  6]
 [15  7 15 11]
 [ 3  7 19 11]
 [12 20  8 17]]
Masked Array: 
[[1 10 -- 6]
 [-- 7 -- --]
 [3 7 -- --]
 [-- -- 8 --]]
Sum of unmasked elements:  42


In [26]:
## 20th answer

array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original Array: ")
print(array)
print("Masked Array: ")
print(masked_array)

mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified Masked Array: ")
print(masked_array)

Original Array: 
[[12 14 16]
 [19 12 20]
 [ 2  4  2]]
Masked Array: 
[[-- 14 16]
 [19 -- 20]
 [2 4 --]]
Modified Masked Array: 
[[12 14 16]
 [19 12 20]
 [ 2  4 12]]
